# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\"\x07\n\x05\x45mpty\"8\n\x12RequestVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\x05\"9\n\x13RequestVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\"^\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x11\n\tleader_id\x18\x02 \x01(\x05\x12\x0f\n\x07\x65ntries\x18\x03 \x03(\t\x12\x14\n\x0c\x63ommit_index\x18\x04 \x01(\x05\"6\n\x15\x41ppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\"@\n\x13NotifyLeaderRequest\x12\x11\n\tleader_id\x18\x01 \x01(\x05\x12\x16\n\x0eleader_address\x18\x02 \x01(\t\"\"\n\rClientRequest\x12\x11\n\toperation\x18\x01 \x01(\t\"\x12\n\x03\x41\x63k\x12\x0b\n\x03msg\x18\x01 \x01(\t2\x84\x02\n\x0bRaftService\x12\x42\n\x0bRequestVote\x12\x18.raft.RequestVoteRequest\x1a\x19.raft.RequestVoteResponse\x12H\n\rAppendEntries\x12\x1a.raft.AppendEntriesRequest\x1a\x1b.raft.AppendEntriesResponse\x12\x34\n\x0cNotifyLeader\x12\x19.raft.NotifyLeaderRequest\x1a\t.raft.Ack\x12\x31\n\x0f\x43lientOperation\x12\x13.raft.ClientRequest\x1a\t.raft.AckB\x0fZ\r./proto;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\r./proto;proto'
  _globals['_EMPTY']._serialized_start=20
  _globals['_EMPTY']._serialized_end=27
  _globals['_REQUESTVOTEREQUEST']._serialized_start=29
  _globals['_REQUESTVOTEREQUEST']._serialized_end=85
  _globals['_REQUESTVOTERESPONSE']._serialized_start=87
  _globals['_REQUESTVOTERESPONSE']._serialized_end=144
  _globals['_APPENDENTRIESREQUEST']._serialized_start=146
  _globals['_APPENDENTRIESREQUEST']._serialized_end=240
  _globals['_APPENDENTRIESRESPONSE']._serialized_start=242
  _globals['_APPENDENTRIESRESPONSE']._serialized_end=296
  _globals['_NOTIFYLEADERREQUEST']._serialized_start=298
  _globals['_NOTIFYLEADERREQUEST']._serialized_end=362
  _globals['_CLIENTREQUEST']._serialized_start=364
  _globals['_CLIENTREQUEST']._serialized_end=398
  _globals['_ACK']._serialized_start=400
  _globals['_ACK']._serialized_end=418
  _globals['_RAFTSERVICE']._serialized_start=421
  _globals['_RAFTSERVICE']._serialized_end=681
# @@protoc_insertion_point(module_scope)
